import { APP_IMAGES } from "@/assets";
import { IWorks } from "@/shared/interfaces";

export const myWorks: IWorks[] = [
  {
    name: "PPA",
    description: {
      pt: "Sistema desenvolvido para o controle de gastos anuais distribuídos para os municípios do estado do Acre.",
      en: "System developed to control annual expenses distributed to municipalities in the state of Acre.",
    },
    image: APP_IMAGES.ppaLogo,
    imageW: 100,
    imageH: 100,
    type: "professional",
    technologiesIndexList: [3, 5, 7],
    id: 0,
  },
  {
    name: "DETRAN|ES",
    description: {
      pt: "Sistema desenvolvido para o DETRAN do estado do Espírito Santo com o objetivo de unificar outros sistemas internos melhorando a usabilidade dos usuários do órgão público.",
      en: "System developed for DETRAN of the state of Espírito Santo with the objective of unifying other internal systems, improving usability for users of the public body.",
    },
    image: APP_IMAGES.detranLogo,
    imageW: 150,
    imageH: 100,
    type: "professional",
    technologiesIndexList: [3, 5, 7],
    id: 1,
  },
  {
    name: "HUB",
    description: {
      pt: "Projeto interno desenvolvido para controle de alocação de horas de funcionários da equipe de desenvolvimento e gestão de perfil técnico.",
      en: "Internal project developed to control the allocation of hours for employees in the development team and technical profile management.",
    },
    image: APP_IMAGES.hubLogo,
    imageW: 150,
    imageH: 100,
    type: "professional",
    technologiesIndexList: [3, 5, 7, 24],
    id: 2,
    cmmi: true,
  },
  {
    name: "VINTDESK",
    description: {
      pt: "Projeto interno desenvolvido para controle de agendamento de mesas para funcionários dos setores da empresa.",
      en: "Internal project developed to control table scheduling for employees in the company's sectors.",
    },
    image: APP_IMAGES.vintLogo,
    imageW: 100,
    imageH: 100,
    type: "professional",
    technologiesIndexList: [3, 5, 6, 10],
    id: 3,
    cmmi: true,
  },
  {
    name: "SGC",
    description: {
      pt: "Projeto interno desenvolvido para gestão de LNC de funcionários.",
      en: "Internal project developed for employee LNC management.",
    },
    image: APP_IMAGES.sgcLogo,
    imageW: 100,
    imageH: 100,
    type: "professional",
    technologiesIndexList: [3, 5, 8],
    id: 4,
    cmmi: true,
  },
  {
    name: "Calculadora React",
    description: {
      pt: "Projeto desenvolvido para estudos em React onde está sendo simulado as funcionalidades de uma calculadora.",
      en: "Project developed for studies in React where the functionalities of a calculator are being simulated.",
    },
    image: APP_IMAGES.calcLogo,
    imageW: 250,
    imageH: 150,
    type: "personal",
    technologiesIndexList: [4, 6],
    id: 5,
    link: "https://calculator-react-brown.vercel.app/",
    repository: "https://github.com/LuanSOliveira/calculator-react",
  },
  {
    name: "Projeto Kanban",
    description: {
      pt: "Projeto desenvolvido para estudos em React onde está sendo simulado as funcionalidades de uma To do List (Kanban).",
      en: "Project developed for studies in React where the functionalities of a To do List (Kanban) are being simulated.",
    },
    image: APP_IMAGES.kanbanLogo,
    imageW: 250,
    imageH: 150,
    type: "personal",
    technologiesIndexList: [4, 6, 2, 24],
    id: 6,
    link: "https://projeto-kanban.vercel.app/",
    repository: "https://github.com/LuanSOliveira/Projeto-Kanban",
  },
  {
    name: "Minhas Residêcias",
    description: {
      pt: "Projeto desenvolvido para uso pessoal onde é possível gerênciar residências locadas.",
      en: "Project developed for personal use where it is possible to manage rented residences.",
    },
    image: APP_IMAGES.homeLogo,
    imageW: 250,
    imageH: 150,
    type: "personal",
    technologiesIndexList: [4, 6, 2, 15],
    id: 7,
    link: "https://gerenciador-de-residencias.vercel.app/",
    repository: "https://github.com/LuanSOliveira/gerenciador-de-residencias",
  },
];
